import { Box, ChevronDown, CircleDot, Rotate3d, Scaling, SlidersHorizontal } from 'lucide-react'

function VectorInput({ label, values, onChange }) {
  return <div className="modeling-vector-input"><span>{label}</span>{['X', 'Y', 'Z'].map((axis, index) => <label key={axis}><em>{axis}</em><input type="number" step="0.01" value={Number(values?.[index] ?? 0).toFixed(2)} onChange={(event) => { const next = [...(values || [0, 0, 0])]; next[index] = Number(event.target.value); onChange(next) }} aria-label={`${label} ${axis}`} /></label>)}</div>
}

export function StudioProperties({ node, onUpdateNode, onDuplicateNode, onDeleteNode, onMaterialChange }) {
  if (!node) return <section className="modeling-properties"><div className="modeling-panel-heading compact"><div><span className="modeling-panel-kicker">Properties</span><h2>Inspector</h2></div><SlidersHorizontal size={16} /></div><div className="modeling-inspector-empty"><CircleDot size={22} /><p>Select an object in the viewport or outliner.</p></div></section>
  return <section className="modeling-properties" aria-label="Object properties">
    <div className="modeling-panel-heading compact"><div><span className="modeling-panel-kicker">Properties</span><h2>{node.name}</h2></div><Box size={16} /></div>
    <details open><summary><Rotate3d size={14} /> Transform <ChevronDown size={13} /></summary><div className="modeling-property-body"><VectorInput label="Location" values={node.position} onChange={(value) => onUpdateNode({ position: value })} /><VectorInput label="Rotation" values={node.rotation} onChange={(value) => onUpdateNode({ rotation: value })} /><VectorInput label="Scale" values={node.scale} onChange={(value) => onUpdateNode({ scale: value })} /></div></details>
    <details open><summary><CircleDot size={14} /> Material <ChevronDown size={13} /></summary><div className="modeling-property-body">{node.materialColor ? <label className="modeling-property-row"><span>Base color</span><input type="color" value={node.materialColor} onChange={(event) => { onUpdateNode({ materialColor: event.target.value }); onMaterialChange?.({ color: event.target.value }) }} /></label> : <p className="modeling-muted-copy">This object has no editable material.</p>}<label className="modeling-property-row"><span>Metalness</span><input type="range" min="0" max="1" step="0.01" value={node.metalness ?? 0} onChange={(event) => { const value = Number(event.target.value); onUpdateNode({ metalness: value }); onMaterialChange?.({ metalness: value }) }} /><output>{Number(node.metalness ?? 0).toFixed(2)}</output></label><label className="modeling-property-row"><span>Roughness</span><input type="range" min="0" max="1" step="0.01" value={node.roughness ?? 0.5} onChange={(event) => { const value = Number(event.target.value); onUpdateNode({ roughness: value }); onMaterialChange?.({ roughness: value }) }} /><output>{Number(node.roughness ?? 0.5).toFixed(2)}</output></label></div></details>
    <details><summary><Scaling size={14} /> Modeling tools <ChevronDown size={13} /></summary><div className="modeling-property-body"><div className="modeling-property-actions"><button type="button" className="modeling-secondary-button" onClick={onDuplicateNode}>Duplicate</button><button type="button" className="modeling-secondary-button" onClick={onDeleteNode}>Delete</button></div><label className="modeling-property-row modeling-property-name"><span>Name</span><input value={node.name} onChange={(event) => onUpdateNode({ name: event.target.value })} /></label><p className="modeling-muted-copy">Use the viewport tools to move, rotate, scale, sculpt, or pose this object.</p></div></details>
  </section>
}
