import { ChevronDown, Circle, Pause, Play, Plus, SkipBack, Square } from 'lucide-react'

export function StudioTimeline({ nodes, scene, playing, currentFrame, onTogglePlayback, onFrameChange, onAddKeyframe }) {
  return <section className="modeling-timeline" aria-label="Animation timeline">
    <div className="modeling-timeline-header"><div className="modeling-browser-tabs" role="tablist"><button type="button" className="is-active">Timeline</button><button type="button">Dope Sheet</button><button type="button">Graph Editor</button></div><div className="modeling-timeline-actions"><button type="button" onClick={() => onFrameChange(0)} aria-label="Go to first frame"><SkipBack size={14} /></button><button type="button" onClick={onTogglePlayback} aria-label={playing ? 'Pause animation' : 'Play animation'}>{playing ? <Pause size={14} /> : <Play size={14} />}</button><button type="button" onClick={() => onFrameChange(1)} aria-label="Stop animation"><Square size={12} /></button><button type="button" className="modeling-keyframe-button" onClick={onAddKeyframe}><Plus size={13} /> Keyframe</button></div></div>
    <div className="modeling-timeline-body"><div className="modeling-timeline-labels">{nodes.slice(0, 8).map((node) => <div key={node.id}><ChevronDown size={11} /><Circle size={8} />{node.name}</div>)}{nodes.length === 0 && <p className="modeling-muted-copy">Animation tracks appear when a model is loaded.</p>}</div><div className="modeling-timeline-grid"><div className="modeling-frame-ruler">{[0, 10, 20, 30, 40, 50, 60].map((frame) => <span key={frame}>{frame}</span>)}</div>{nodes.slice(0, 8).map((node) => <div className="modeling-track-row" key={node.id}><button type="button" className="modeling-track-key" onClick={() => onFrameChange(Math.max(0, currentFrame))} aria-label={`Set ${node.name} keyframe`}><span /></button></div>)}</div></div>
    <label className="modeling-frame-slider"><span>Frame {currentFrame}</span><input type="range" min="0" max="120" value={currentFrame} onChange={(event) => onFrameChange(Number(event.target.value))} aria-label="Current animation frame" /></label>
    <small className="modeling-timeline-note">{scene.animations?.length || 0} animation clips · keyframe transforms and expressions from the inspector.</small>
  </section>
}
