import {
  AppWindow,
  Blocks,
  Bot,
  Brain,
  BriefcaseBusiness,
  CalendarClock,
  CalendarDays,
  ChartNoAxesCombined,
  Code2,
  Contact,
  Files,
  FolderKanban,
  History,
  LayoutDashboard,
  LayoutTemplate,
  ListTodo,
  Mail,
  MessageCircle,
  MessageSquare,
  Palette,
  Phone,
  PhoneCall,
  Rocket,
  Settings,
  Smile,
  SquareTerminal,
  UserRound,
} from 'lucide-react'

export const navigationItems = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, group: 'Work', module: 'work' },
  { id: 'todo', label: 'Todo List', icon: ListTodo, group: 'Work', module: 'todo' },
  { id: 'projects', label: 'Projects', icon: FolderKanban, group: 'Work', module: 'projects' },
  { id: 'documents', label: 'Documents', icon: Files, group: 'Work', module: 'documents' },
  { id: 'workspace', label: 'Workspace', icon: SquareTerminal, group: 'Work', module: 'workspace' },
  { id: 'studio', label: 'Studio', icon: Blocks, group: 'Studio', module: 'studio' },
  { id: 'studio-apps', label: 'Apps', icon: AppWindow, group: 'Studio', module: 'studio' },
  { id: 'studio-templates', label: 'Templates', icon: LayoutTemplate, group: 'Studio', module: 'studio' },
  { id: 'eve', label: 'Chat', icon: Bot, group: 'Eve AI', module: 'eve' },
  { id: 'avatar', label: 'Avatar Studio', icon: Smile, group: 'Eve AI', module: 'eve' },
  { id: 'eve-sessions', label: 'Chat Sessions', icon: History, group: 'Eve AI', module: 'eve' },
  { id: 'eve-memory', label: 'Eve Memory', icon: Brain, group: 'Eve AI', module: 'eve' },
  { id: 'eve-call', label: 'Voice & AI Call', icon: PhoneCall, group: 'Eve AI', module: 'eve' },
  { id: 'eve-schedules', label: 'Schedules & Reminders', icon: CalendarClock, group: 'Eve AI', module: 'eve' },
  { id: 'competitive-coding', label: 'Competitive Coding', icon: Code2, group: 'Growth', module: 'growth' },
  { id: 'hackathons', label: 'Hackathons', icon: Rocket, group: 'Growth', module: 'growth' },
  { id: 'jobs', label: 'Jobs', icon: BriefcaseBusiness, group: 'Growth', module: 'growth' },
  { id: 'stats', label: 'Stats', icon: ChartNoAxesCombined, group: 'Growth', module: 'growth' },
  { id: 'calendar', label: 'Calendar', icon: CalendarDays, group: 'Communication', module: 'calendar' },
  { id: 'mails', label: 'Mail', icon: Mail, group: 'Communication', module: 'mail' },
  { id: 'whatsapp', label: 'WhatsApp', icon: MessageCircle, group: 'Communication', module: 'whatsapp' },
  { id: 'chats', label: 'Chats', icon: MessageSquare, group: 'Communication', module: 'chats' },
  { id: 'calls', label: 'Calls', icon: Phone, group: 'Communication', module: 'calls' },
  { id: 'contacts', label: 'Contacts', icon: Contact, group: 'Communication', module: 'contacts' },
  { id: 'profile', label: 'Profile', icon: UserRound, group: 'Account', module: 'account' },
  { id: 'themes', label: 'Themes', icon: Palette, group: 'Account', module: 'account' },
  { id: 'setting', label: 'Settings', icon: Settings, group: 'Account', module: 'account' },
  { id: 'usage', label: 'Usage', icon: ChartNoAxesCombined, group: 'Account', module: 'account' },
]

export const GROUP_MODULE_MAP = {
  Work: 'work',
  Studio: 'studio',
  'Eve AI': 'eve',
  Growth: 'growth',
  Communication: 'comm',
  Account: 'account',
}

export function getGroupModuleKey(group) {
  return GROUP_MODULE_MAP[group] || 'work'
}

