import { useEffect, useState, useCallback } from 'react'

export const THEME_PRESETS = {
  light: {
    id: 'light',
    mode: 'light',
    palette: 'mono',
    name: 'Default Light',
    description: 'Clean monochrome off-white theme',
    colors: {
      '--bg-primary': '#f4f4f5',
      '--bg-secondary': '#ececec',
      '--bg-tertiary': '#e4e4e7',
      '--bg-card': '#fafafa',
      '--bg-card-hover': '#f0f0f2',
      '--bg-hover': '#e4e4e7',
      '--bg-overlay': '#fafafa',
      '--text-primary': '#09090b',
      '--text-secondary': '#52525b',
      '--text-muted': '#71717a',
      '--text-inverse': '#f4f4f5',
      '--color-primary': '#18181b',
      '--color-primary-hover': '#09090b',
      '--color-primary-light': '#e4e4e7',
      '--color-accent': '#18181b',
      '--border-color': '#e4e4e7',
      '--border-light': '#ececec',
      '--border-heavy': '#a1a1aa',
      '--border-focus': '#71717a',
      '--scrollbar-track': '#e4e4e7',
      '--scrollbar-thumb': '#a1a1aa',
      '--scrollbar-thumb-hover': '#18181b',
      '--color-success': '#18181b',
      '--color-warning': '#71717a',
      '--color-danger': '#18181b',
      '--color-purple': '#71717a',
    },
  },
  dark: {
    id: 'dark',
    mode: 'dark',
    palette: 'mono',
    name: 'Default Dark',
    description: 'Sleek dark monochrome theme',
    colors: {
      '--bg-primary': '#080808',
      '--bg-secondary': '#121212',
      '--bg-tertiary': '#1a1a1a',
      '--bg-card': '#141414',
      '--bg-card-hover': '#1f1f1f',
      '--bg-hover': '#222222',
      '--bg-overlay': '#141414',
      '--text-primary': '#e4e4e7',
      '--text-secondary': '#a1a1aa',
      '--text-muted': '#71717a',
      '--text-inverse': '#09090b',
      '--color-primary': '#f4f4f5',
      '--color-primary-hover': '#ffffff',
      '--color-primary-light': '#222222',
      '--color-accent': '#f4f4f5',
      '--border-color': '#27272a',
      '--border-light': '#1e1e1e',
      '--border-heavy': '#3f3f46',
      '--border-focus': '#71717a',
      '--scrollbar-track': '#141414',
      '--scrollbar-thumb': '#52525b',
      '--scrollbar-thumb-hover': '#a1a1aa',
      '--color-success': '#f4f4f5',
      '--color-warning': '#a1a1aa',
      '--color-danger': '#f4f4f5',
      '--color-purple': '#a1a1aa',
    },
  },
  oled: {
    id: 'oled',
    mode: 'dark',
    palette: 'mono',
    name: 'OLED Pitch Black',
    description: 'Ultra dark #000000 background for max contrast',
    colors: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#050505',
      '--bg-tertiary': '#0d0d0d',
      '--bg-card': '#0a0a0a',
      '--bg-card-hover': '#141414',
      '--bg-hover': '#181818',
      '--bg-overlay': '#0a0a0a',
      '--text-primary': '#ffffff',
      '--text-secondary': '#b0b0b8',
      '--text-muted': '#757580',
      '--text-inverse': '#000000',
      '--color-primary': '#ffffff',
      '--color-primary-hover': '#e6e6e6',
      '--color-primary-light': '#1f1f1f',
      '--color-accent': '#ffffff',
      '--border-color': '#222226',
      '--border-light': '#17171a',
      '--border-heavy': '#44444c',
      '--border-focus': '#888896',
      '--scrollbar-track': '#050505',
      '--scrollbar-thumb': '#44444c',
      '--scrollbar-thumb-hover': '#888896',
      '--color-success': '#ffffff',
      '--color-warning': '#aaaaaa',
      '--color-danger': '#ffffff',
      '--color-purple': '#cccccc',
    },
  },
  midnight: {
    id: 'midnight',
    mode: 'dark',
    palette: 'tri',
    name: 'Midnight Cobalt',
    description: 'Deep navy background with blue highlights',
    colors: {
      '--bg-primary': '#0a0f1d',
      '--bg-secondary': '#0e162a',
      '--bg-tertiary': '#14203a',
      '--bg-card': '#11192e',
      '--bg-card-hover': '#182442',
      '--bg-hover': '#1e2d50',
      '--bg-overlay': '#11192e',
      '--text-primary': '#f0f6ff',
      '--text-secondary': '#93c5fd',
      '--text-muted': '#60a5fa',
      '--text-inverse': '#0a0f1d',
      '--color-primary': '#3b82f6',
      '--color-primary-hover': '#2563eb',
      '--color-primary-light': '#1e3a8a',
      '--color-accent': '#60a5fa',
      '--border-color': '#1e293b',
      '--border-light': '#172033',
      '--border-heavy': '#334155',
      '--border-focus': '#3b82f6',
      '--scrollbar-track': '#0e162a',
      '--scrollbar-thumb': '#334155',
      '--scrollbar-thumb-hover': '#3b82f6',
      '--color-success': '#10b981',
      '--color-warning': '#f59e0b',
      '--color-danger': '#ef4444',
      '--color-purple': '#8b5cf6',
    },
  },
  emerald: {
    id: 'emerald',
    mode: 'dark',
    palette: 'tri',
    name: 'Emerald Cyber',
    description: 'Dark forest background with emerald mint accents',
    colors: {
      '--bg-primary': '#091410',
      '--bg-secondary': '#0f1d18',
      '--bg-tertiary': '#162922',
      '--bg-card': '#12221c',
      '--bg-card-hover': '#1a3028',
      '--bg-hover': '#224035',
      '--bg-overlay': '#12221c',
      '--text-primary': '#ecfdf5',
      '--text-secondary': '#a7f3d0',
      '--text-muted': '#6ee7b7',
      '--text-inverse': '#091410',
      '--color-primary': '#10b981',
      '--color-primary-hover': '#059669',
      '--color-primary-light': '#064e3b',
      '--color-accent': '#34d399',
      '--border-color': '#14382c',
      '--border-light': '#0f2920',
      '--border-heavy': '#1f4d3d',
      '--border-focus': '#10b981',
      '--scrollbar-track': '#0f1d18',
      '--scrollbar-thumb': '#1f4d3d',
      '--scrollbar-thumb-hover': '#10b981',
      '--color-success': '#10b981',
      '--color-warning': '#f59e0b',
      '--color-danger': '#f43f5e',
      '--color-purple': '#a855f7',
    },
  },
  amber: {
    id: 'amber',
    mode: 'dark',
    palette: 'tetra',
    name: 'Cyberpunk Amber',
    description: 'Warm obsidian background with amber gold glow',
    colors: {
      '--bg-primary': '#14110c',
      '--bg-secondary': '#1c1913',
      '--bg-tertiary': '#26221a',
      '--bg-card': '#1f1b14',
      '--bg-card-hover': '#2a251c',
      '--bg-hover': '#363024',
      '--bg-overlay': '#1f1b14',
      '--text-primary': '#fffbeb',
      '--text-secondary': '#fde68a',
      '--text-muted': '#fcd34d',
      '--text-inverse': '#14110c',
      '--color-primary': '#f59e0b',
      '--color-primary-hover': '#d97706',
      '--color-primary-light': '#78350f',
      '--color-accent': '#fbbf24',
      '--border-color': '#3a3123',
      '--border-light': '#292218',
      '--border-heavy': '#544733',
      '--border-focus': '#f59e0b',
      '--scrollbar-track': '#1c1913',
      '--scrollbar-thumb': '#544733',
      '--scrollbar-thumb-hover': '#f59e0b',
      '--color-success': '#22c55e',
      '--color-warning': '#f59e0b',
      '--color-danger': '#ef4444',
      '--color-purple': '#d946ef',
    },
  },
  violet: {
    id: 'violet',
    mode: 'dark',
    palette: 'tri',
    name: 'Violet Glow',
    description: 'Deep violet dark theme with electric purple highlights',
    colors: {
      '--bg-primary': '#110d1c',
      '--bg-secondary': '#171226',
      '--bg-tertiary': '#211a36',
      '--bg-card': '#1a142b',
      '--bg-card-hover': '#241c3c',
      '--bg-hover': '#30264e',
      '--bg-overlay': '#1a142b',
      '--text-primary': '#f5f3ff',
      '--text-secondary': '#ddd6fe',
      '--text-muted': '#c4b5fd',
      '--text-inverse': '#110d1c',
      '--color-primary': '#8b5cf6',
      '--color-primary-hover': '#7c3aed',
      '--color-primary-light': '#4c1d95',
      '--color-accent': '#a78bfa',
      '--border-color': '#2e234a',
      '--border-light': '#211936',
      '--border-heavy': '#43346c',
      '--border-focus': '#8b5cf6',
      '--scrollbar-track': '#171226',
      '--scrollbar-thumb': '#43346c',
      '--scrollbar-thumb-hover': '#8b5cf6',
      '--color-success': '#10b981',
      '--color-warning': '#f59e0b',
      '--color-danger': '#f43f5e',
      '--color-purple': '#8b5cf6',
    },
  },
  nordic: {
    id: 'nordic',
    mode: 'dark',
    palette: 'tri',
    name: 'Nordic Frost',
    description: 'Cool slate grey theme with icy arctic blue highlights',
    colors: {
      '--bg-primary': '#0f172a',
      '--bg-secondary': '#1e293b',
      '--bg-tertiary': '#334155',
      '--bg-card': '#1e293b',
      '--bg-card-hover': '#334155',
      '--bg-hover': '#475569',
      '--bg-overlay': '#1e293b',
      '--text-primary': '#f8fafc',
      '--text-secondary': '#cbd5e1',
      '--text-muted': '#94a3b8',
      '--text-inverse': '#0f172a',
      '--color-primary': '#38bdf8',
      '--color-primary-hover': '#0ea5e9',
      '--color-primary-light': '#0c4a6e',
      '--color-accent': '#7dd3fc',
      '--border-color': '#334155',
      '--border-light': '#1e293b',
      '--border-heavy': '#475569',
      '--border-focus': '#38bdf8',
      '--scrollbar-track': '#1e293b',
      '--scrollbar-thumb': '#475569',
      '--scrollbar-thumb-hover': '#38bdf8',
      '--color-success': '#34d399',
      '--color-warning': '#fbbf24',
      '--color-danger': '#f87171',
      '--color-purple': '#c084fc',
    },
  },
  rose: {
    id: 'rose',
    mode: 'dark',
    palette: 'duo',
    name: 'Rose Obsidian',
    description: 'Velvet dark theme with rose gold and crimson highlights',
    colors: {
      '--bg-primary': '#140b10',
      '--bg-secondary': '#1f1118',
      '--bg-tertiary': '#2b1822',
      '--bg-card': '#22121b',
      '--bg-card-hover': '#2e1925',
      '--bg-hover': '#3c2131',
      '--bg-overlay': '#22121b',
      '--text-primary': '#fff1f2',
      '--text-secondary': '#fecdd3',
      '--text-muted': '#fda4af',
      '--text-inverse': '#140b10',
      '--color-primary': '#f43f5e',
      '--color-primary-hover': '#e11d48',
      '--color-primary-light': '#881337',
      '--color-accent': '#fb7185',
      '--border-color': '#3a1d2d',
      '--border-light': '#291420',
      '--border-heavy': '#50263e',
      '--border-focus': '#f43f5e',
      '--scrollbar-track': '#1f1118',
      '--scrollbar-thumb': '#50263e',
      '--scrollbar-thumb-hover': '#f43f5e',
      '--color-success': '#10b981',
      '--color-warning': '#f59e0b',
      '--color-danger': '#f43f5e',
      '--color-purple': '#e879f9',
    },
  },
  solar: {
    id: 'solar',
    mode: 'light',
    palette: 'duo',
    name: 'Solar Parchment',
    description: 'Warm sepia parchment theme with deep amber typography',
    colors: {
      '--bg-primary': '#fbf7ee',
      '--bg-secondary': '#f3edd9',
      '--bg-tertiary': '#e8dfc4',
      '--bg-card': '#f6f0df',
      '--bg-card-hover': '#ede5cd',
      '--bg-hover': '#e2d7ba',
      '--bg-overlay': '#f6f0df',
      '--text-primary': '#2d241e',
      '--text-secondary': '#5c4d41',
      '--text-muted': '#8c7b6d',
      '--text-inverse': '#fbf7ee',
      '--color-primary': '#b45309',
      '--color-primary-hover': '#92400e',
      '--color-primary-light': '#fef3c7',
      '--color-accent': '#d97706',
      '--border-color': '#e2d5b8',
      '--border-light': '#ece1c8',
      '--border-heavy': '#c7b693',
      '--border-focus': '#b45309',
      '--scrollbar-track': '#f3edd9',
      '--scrollbar-thumb': '#c7b693',
      '--scrollbar-thumb-hover': '#b45309',
      '--color-success': '#15803d',
      '--color-warning': '#b45309',
      '--color-danger': '#b91c1c',
      '--color-purple': '#7e22ce',
    },
  },
  matrix: {
    id: 'matrix',
    mode: 'dark',
    palette: 'duo',
    name: 'Matrix Lime',
    description: 'Deep terminal obsidian theme with electric matrix neon lime',
    colors: {
      '--bg-primary': '#080f0a',
      '--bg-secondary': '#0d1911',
      '--bg-tertiary': '#14261a',
      '--bg-card': '#102015',
      '--bg-card-hover': '#172c1e',
      '--bg-hover': '#1f3b28',
      '--bg-overlay': '#102015',
      '--text-primary': '#f7fee7',
      '--text-secondary': '#bef264',
      '--text-muted': '#84cc16',
      '--text-inverse': '#080f0a',
      '--color-primary': '#84cc16',
      '--color-primary-hover': '#65a30d',
      '--color-primary-light': '#1a2e05',
      '--color-accent': '#a3e635',
      '--border-color': '#1e3a24',
      '--border-light': '#152919',
      '--border-heavy': '#2d5635',
      '--border-focus': '#84cc16',
      '--scrollbar-track': '#0d1911',
      '--scrollbar-thumb': '#2d5635',
      '--scrollbar-thumb-hover': '#84cc16',
      '--color-success': '#84cc16',
      '--color-warning': '#eab308',
      '--color-danger': '#ef4444',
      '--color-purple': '#a855f7',
    },
  },
  synthwave: {
    id: 'synthwave',
    mode: 'dark',
    palette: 'tetra',
    name: 'Synthwave Sunset',
    description: '80s retro dark theme with glowing magenta and cyan accents',
    colors: {
      '--bg-primary': '#120824',
      '--bg-secondary': '#1a0c33',
      '--bg-tertiary': '#251247',
      '--bg-card': '#1d0d3a',
      '--bg-card-hover': '#28134e',
      '--bg-hover': '#361a69',
      '--bg-overlay': '#1d0d3a',
      '--text-primary': '#fdf4ff',
      '--text-secondary': '#f5d0fe',
      '--text-muted': '#f0abfc',
      '--text-inverse': '#120824',
      '--color-primary': '#ec4899',
      '--color-primary-hover': '#db2777',
      '--color-primary-light': '#701a75',
      '--color-accent': '#06b6d4',
      '--border-color': '#3c1968',
      '--border-light': '#291147',
      '--border-heavy': '#572496',
      '--border-focus': '#ec4899',
      '--scrollbar-track': '#1a0c33',
      '--scrollbar-thumb': '#572496',
      '--scrollbar-thumb-hover': '#ec4899',
      '--color-success': '#10b981',
      '--color-warning': '#f59e0b',
      '--color-danger': '#f43f5e',
      '--color-purple': '#d946ef',
    },
  },
  candy: {
    id: 'candy',
    mode: 'light',
    palette: 'duo',
    name: 'Candy Frost',
    description: 'Soft pastel pink theme with rosy plum typography',
    colors: {
      '--bg-primary': '#fdf6f7',
      '--bg-secondary': '#f9ecee',
      '--bg-tertiary': '#f3dde2',
      '--bg-card': '#fffafb',
      '--bg-card-hover': '#f9eef0',
      '--bg-hover': '#f3dde2',
      '--bg-overlay': '#fffafb',
      '--text-primary': '#3a2328',
      '--text-secondary': '#7d5b63',
      '--text-muted': '#a1848c',
      '--text-inverse': '#fffafb',
      '--color-primary': '#d6336c',
      '--color-primary-hover': '#b4255a',
      '--color-primary-light': '#fbe0e8',
      '--color-accent': '#ec4899',
      '--border-color': '#f1d8de',
      '--border-light': '#f7e6ea',
      '--border-heavy': '#d9b0bc',
      '--border-focus': '#d6336c',
      '--scrollbar-track': '#f9ecee',
      '--scrollbar-thumb': '#d9b0bc',
      '--scrollbar-thumb-hover': '#d6336c',
      '--color-success': '#2f9e64',
      '--color-warning': '#c2410c',
      '--color-danger': '#c41e2f',
      '--color-purple': '#7c3aed',
    },
  },
  ocean: {
    id: 'ocean',
    mode: 'dark',
    palette: 'tri',
    name: 'Tidal Cyan',
    description: 'Deep ocean dark theme with electric cyan highlights',
    colors: {
      '--bg-primary': '#08131a',
      '--bg-secondary': '#0d1d26',
      '--bg-tertiary': '#142a36',
      '--bg-card': '#0f202a',
      '--bg-card-hover': '#162d3a',
      '--bg-hover': '#1c3a4a',
      '--bg-overlay': '#0f202a',
      '--text-primary': '#ecfeff',
      '--text-secondary': '#a5f3fc',
      '--text-muted': '#67e8f9',
      '--text-inverse': '#08131a',
      '--color-primary': '#22d3ee',
      '--color-primary-hover': '#06b6d4',
      '--color-primary-light': '#164e63',
      '--color-accent': '#67e8f9',
      '--border-color': '#1c3a4a',
      '--border-light': '#142a36',
      '--border-heavy': '#2a5568',
      '--border-focus': '#22d3ee',
      '--scrollbar-track': '#0d1d26',
      '--scrollbar-thumb': '#2a5568',
      '--scrollbar-thumb-hover': '#22d3ee',
      '--color-success': '#10b981',
      '--color-warning': '#f59e0b',
      '--color-danger': '#f43f5e',
      '--color-purple': '#818cf8',
    },
  },
  dune: {
    id: 'dune',
    mode: 'light',
    palette: 'duo',
    name: 'Dune Gold',
    description: 'Bright golden desert sand theme with rich honey accents',
    colors: {
      '--bg-primary': '#faf6ee',
      '--bg-secondary': '#f4ecdd',
      '--bg-tertiary': '#eadfc8',
      '--bg-card': '#fdf9f1',
      '--bg-card-hover': '#f3ecdc',
      '--bg-hover': '#e6d9bd',
      '--bg-overlay': '#fdf9f1',
      '--text-primary': '#43331f',
      '--text-secondary': '#7c6847',
      '--text-muted': '#a18a63',
      '--text-inverse': '#fdf9f1',
      '--color-primary': '#a16207',
      '--color-primary-hover': '#854d0e',
      '--color-primary-light': '#fef3c7',
      '--color-accent': '#ca8a04',
      '--border-color': '#e6d9bd',
      '--border-light': '#efe6d2',
      '--border-heavy': '#c9b489',
      '--border-focus': '#a16207',
      '--scrollbar-track': '#f4ecdd',
      '--scrollbar-thumb': '#c9b489',
      '--scrollbar-thumb-hover': '#a16207',
      '--color-success': '#15803d',
      '--color-warning': '#a16207',
      '--color-danger': '#b91c1c',
      '--color-purple': '#7e22ce',
    },
  },
  graphite: {
    id: 'graphite',
    mode: 'light',
    palette: 'mono',
    name: 'Graphite Steel',
    description: 'Cool industrial grey theme with gunmetal surfaces',
    colors: {
      '--bg-primary': '#f2f3f5',
      '--bg-secondary': '#e8eaee',
      '--bg-tertiary': '#dde0e6',
      '--bg-card': '#f8f9fb',
      '--bg-card-hover': '#eef0f4',
      '--bg-hover': '#dde0e6',
      '--bg-overlay': '#f8f9fb',
      '--text-primary': '#1c2126',
      '--text-secondary': '#4b5560',
      '--text-muted': '#6b7680',
      '--text-inverse': '#f8f9fb',
      '--color-primary': '#23272d',
      '--color-primary-hover': '#111418',
      '--color-primary-light': '#e4e7eb',
      '--color-accent': '#4b5560',
      '--border-color': '#dde0e6',
      '--border-light': '#e6e9ee',
      '--border-heavy': '#aab2bd',
      '--border-focus': '#4b5560',
      '--scrollbar-track': '#e8eaee',
      '--scrollbar-thumb': '#aab2bd',
      '--scrollbar-thumb-hover': '#23272d',
      '--color-success': '#1f6f50',
      '--color-warning': '#9a6a00',
      '--color-danger': '#b91c1c',
      '--color-purple': '#6d5bb8',
    },
  },
  wine: {
    id: 'wine',
    mode: 'dark',
    palette: 'duo',
    name: 'Burgundy Noir',
    description: 'Velvet dark wine theme with crimson berry highlights',
    colors: {
      '--bg-primary': '#14070d',
      '--bg-secondary': '#1d0c15',
      '--bg-tertiary': '#2a1120',
      '--bg-card': '#200e18',
      '--bg-card-hover': '#2a1420',
      '--bg-hover': '#361a2b',
      '--bg-overlay': '#200e18',
      '--text-primary': '#fdf2f5',
      '--text-secondary': '#e7b8c3',
      '--text-muted': '#c98a9a',
      '--text-inverse': '#14070d',
      '--color-primary': '#b8405a',
      '--color-primary-hover': '#9c2f49',
      '--color-primary-light': '#4a1526',
      '--color-accent': '#d45d78',
      '--border-color': '#3a1826',
      '--border-light': '#2a101d',
      '--border-heavy': '#5a2338',
      '--border-focus': '#b8405a',
      '--scrollbar-track': '#1d0c15',
      '--scrollbar-thumb': '#5a2338',
      '--scrollbar-thumb-hover': '#b8405a',
      '--color-success': '#2f9e64',
      '--color-warning': '#c47f1d',
      '--color-danger': '#c41e2f',
      '--color-purple': '#9b6bb5',
    },
  },
  coffee: {
    id: 'coffee',
    mode: 'dark',
    palette: 'duo',
    name: 'Espresso Roast',
    description: 'Warm roasted coffee theme with caramel highlights',
    colors: {
      '--bg-primary': '#120e0b',
      '--bg-secondary': '#1a1410',
      '--bg-tertiary': '#241c15',
      '--bg-card': '#1d1612',
      '--bg-card-hover': '#281e17',
      '--bg-hover': '#33261c',
      '--bg-overlay': '#1d1612',
      '--text-primary': '#f7f0e7',
      '--text-secondary': '#d4c1a8',
      '--text-muted': '#b09574',
      '--text-inverse': '#120e0b',
      '--color-primary': '#a3713d',
      '--color-primary-hover': '#8a5b2e',
      '--color-primary-light': '#3b2a19',
      '--color-accent': '#c08a52',
      '--border-color': '#35281d',
      '--border-light': '#261c14',
      '--border-heavy': '#4f3a28',
      '--border-focus': '#a3713d',
      '--scrollbar-track': '#1a1410',
      '--scrollbar-thumb': '#4f3a28',
      '--scrollbar-thumb-hover': '#a3713d',
      '--color-success': '#4c9e62',
      '--color-warning': '#c47f1d',
      '--color-danger': '#c4451e',
      '--color-purple': '#9b6bb5',
    },
  },
  arctic: {
    id: 'arctic',
    mode: 'light',
    palette: 'duo',
    name: 'Arctic Ice',
    description: 'Pale glacial ice theme with cool arctic blue highlights',
    colors: {
      '--bg-primary': '#f4f8fb',
      '--bg-secondary': '#e9f0f6',
      '--bg-tertiary': '#dbe7f0',
      '--bg-card': '#fafcfe',
      '--bg-card-hover': '#eef4f9',
      '--bg-hover': '#dbe7f0',
      '--bg-overlay': '#fafcfe',
      '--text-primary': '#1f3a4d',
      '--text-secondary': '#4f7086',
      '--text-muted': '#7590a3',
      '--text-inverse': '#fafcfe',
      '--color-primary': '#0e7490',
      '--color-primary-hover': '#155e75',
      '--color-primary-light': '#cbeaf5',
      '--color-accent': '#0891b2',
      '--border-color': '#dbe7f0',
      '--border-light': '#e6eef5',
      '--border-heavy': '#b3c8d6',
      '--border-focus': '#0e7490',
      '--scrollbar-track': '#e9f0f6',
      '--scrollbar-thumb': '#b3c8d6',
      '--scrollbar-thumb-hover': '#0e7490',
      '--color-success': '#1f7a5a',
      '--color-warning': '#a16207',
      '--color-danger': '#b91c1c',
      '--color-purple': '#6d5bb8',
    },
  },
  forest: {
    id: 'forest',
    mode: 'dark',
    palette: 'tri',
    name: 'Forest Canopy',
    description: 'Muted olive forest theme with mossy green highlights',
    colors: {
      '--bg-primary': '#0c120e',
      '--bg-secondary': '#121a14',
      '--bg-tertiary': '#1a251c',
      '--bg-card': '#151f18',
      '--bg-card-hover': '#1c2a21',
      '--bg-hover': '#243527',
      '--bg-overlay': '#151f18',
      '--text-primary': '#f0f7f0',
      '--text-secondary': '#bfd3c2',
      '--text-muted': '#97ad9b',
      '--text-inverse': '#0c120e',
      '--color-primary': '#4e7c58',
      '--color-primary-hover': '#3d6446',
      '--color-primary-light': '#203220',
      '--color-accent': '#6da075',
      '--border-color': '#223021',
      '--border-light': '#1a241b',
      '--border-heavy': '#3a5338',
      '--border-focus': '#4e7c58',
      '--scrollbar-track': '#121a14',
      '--scrollbar-thumb': '#3a5338',
      '--scrollbar-thumb-hover': '#4e7c58',
      '--color-success': '#2f9e64',
      '--color-warning': '#b9951d',
      '--color-danger': '#c4451e',
      '--color-purple': '#8a7cc0',
    },
  },
  tangerine: {
    id: 'tangerine',
    mode: 'light',
    palette: 'duo',
    name: 'Tangerine Pop',
    description: 'Zesty citrus theme with juicy tangerine highlights',
    colors: {
      '--bg-primary': '#fef8f2',
      '--bg-secondary': '#fdf0e3',
      '--bg-tertiary': '#f9e2cd',
      '--bg-card': '#fffbf6',
      '--bg-card-hover': '#fdf2e7',
      '--bg-hover': '#f7ddc2',
      '--bg-overlay': '#fffbf6',
      '--text-primary': '#4a2a14',
      '--text-secondary': '#8a5a33',
      '--text-muted': '#b07e52',
      '--text-inverse': '#fffbf6',
      '--color-primary': '#ea580c',
      '--color-primary-hover': '#c2410c',
      '--color-primary-light': '#ffedd5',
      '--color-accent': '#f97316',
      '--border-color': '#f5dcc2',
      '--border-light': '#f9e8d4',
      '--border-heavy': '#e0b48d',
      '--border-focus': '#ea580c',
      '--scrollbar-track': '#fdf0e3',
      '--scrollbar-thumb': '#e0b48d',
      '--scrollbar-thumb-hover': '#ea580c',
      '--color-success': '#2f9e64',
      '--color-warning': '#c2410c',
      '--color-danger': '#c41e2f',
      '--color-purple': '#7c3aed',
    },
  },
  charcoal: {
    id: 'charcoal',
    mode: 'dark',
    palette: 'mono',
    name: 'Charcoal Ash',
    description: 'Warm charcoal grey theme with soft ash highlights',
    colors: {
      '--bg-primary': '#131316',
      '--bg-secondary': '#1a1a1f',
      '--bg-tertiary': '#232329',
      '--bg-card': '#1c1c21',
      '--bg-card-hover': '#26262c',
      '--bg-hover': '#303038',
      '--bg-overlay': '#1c1c21',
      '--text-primary': '#f0f0f2',
      '--text-secondary': '#b4b4ba',
      '--text-muted': '#82828c',
      '--text-inverse': '#131316',
      '--color-primary': '#e8e8ea',
      '--color-primary-hover': '#ffffff',
      '--color-primary-light': '#2c2c33',
      '--color-accent': '#c9c9cf',
      '--border-color': '#2c2c33',
      '--border-light': '#212127',
      '--border-heavy': '#45454f',
      '--border-focus': '#82828c',
      '--scrollbar-track': '#1a1a1f',
      '--scrollbar-thumb': '#45454f',
      '--scrollbar-thumb-hover': '#82828c',
      '--color-success': '#e8e8ea',
      '--color-warning': '#a1a1a9',
      '--color-danger': '#e8e8ea',
      '--color-purple': '#b4b4ba',
    },
  },
  fog: {
    id: 'fog',
    mode: 'light',
    palette: 'mono',
    name: 'Fog Grey',
    description: 'Cool light grey theme with soft misty surfaces',
    colors: {
      '--bg-primary': '#f5f6f7',
      '--bg-secondary': '#eceef0',
      '--bg-tertiary': '#e2e5e8',
      '--bg-card': '#fafbfc',
      '--bg-card-hover': '#f0f2f4',
      '--bg-hover': '#e2e5e8',
      '--bg-overlay': '#fafbfc',
      '--text-primary': '#1f2429',
      '--text-secondary': '#4a535c',
      '--text-muted': '#6f7a85',
      '--text-inverse': '#fafbfc',
      '--color-primary': '#232a31',
      '--color-primary-hover': '#14181d',
      '--color-primary-light': '#e5e9ed',
      '--color-accent': '#4a535c',
      '--border-color': '#e2e5e8',
      '--border-light': '#eaedf0',
      '--border-heavy': '#aeb8c2',
      '--border-focus': '#4a535c',
      '--scrollbar-track': '#eceef0',
      '--scrollbar-thumb': '#aeb8c2',
      '--scrollbar-thumb-hover': '#232a31',
      '--color-success': '#232a31',
      '--color-warning': '#6f7a85',
      '--color-danger': '#232a31',
      '--color-purple': '#6f7a85',
    },
  },
  silver: {
    id: 'silver',
    mode: 'light',
    palette: 'mono',
    name: 'Silver Mist',
    description: 'Light silvery grey theme with a polished metal feel',
    colors: {
      '--bg-primary': '#eef0f2',
      '--bg-secondary': '#e3e6e9',
      '--bg-tertiary': '#d7dbdf',
      '--bg-card': '#f4f6f7',
      '--bg-card-hover': '#e9ecee',
      '--bg-hover': '#d7dbdf',
      '--bg-overlay': '#f4f6f7',
      '--text-primary': '#2b3035',
      '--text-secondary': '#586068',
      '--text-muted': '#7c858e',
      '--text-inverse': '#f4f6f7',
      '--color-primary': '#2f363d',
      '--color-primary-hover': '#1c2126',
      '--color-primary-light': '#dfe3e6',
      '--color-accent': '#586068',
      '--border-color': '#d7dbdf',
      '--border-light': '#e0e4e7',
      '--border-heavy': '#a6aeb5',
      '--border-focus': '#586068',
      '--scrollbar-track': '#e3e6e9',
      '--scrollbar-thumb': '#a6aeb5',
      '--scrollbar-thumb-hover': '#2f363d',
      '--color-success': '#2f363d',
      '--color-warning': '#7c858e',
      '--color-danger': '#2f363d',
      '--color-purple': '#7c858e',
    },
  },
  stone: {
    id: 'stone',
    mode: 'light',
    palette: 'mono',
    name: 'Stone Grey',
    description: 'Warm neutral grey theme inspired by natural stone',
    colors: {
      '--bg-primary': '#e9e6e2',
      '--bg-secondary': '#dedad4',
      '--bg-tertiary': '#d0cbc3',
      '--bg-card': '#f0ede8',
      '--bg-card-hover': '#e4e0d9',
      '--bg-hover': '#d0cbc3',
      '--bg-overlay': '#f0ede8',
      '--text-primary': '#322f2b',
      '--text-secondary': '#5f5a53',
      '--text-muted': '#837d74',
      '--text-inverse': '#f0ede8',
      '--color-primary': '#37332e',
      '--color-primary-hover': '#23201c',
      '--color-primary-light': '#dcd7cf',
      '--color-accent': '#5f5a53',
      '--border-color': '#d0cbc3',
      '--border-light': '#dcd7cf',
      '--border-heavy': '#a39b90',
      '--border-focus': '#5f5a53',
      '--scrollbar-track': '#dedad4',
      '--scrollbar-thumb': '#a39b90',
      '--scrollbar-thumb-hover': '#37332e',
      '--color-success': '#37332e',
      '--color-warning': '#837d74',
      '--color-danger': '#37332e',
      '--color-purple': '#837d74',
    },
  },
  smoke: {
    id: 'smoke',
    mode: 'dark',
    palette: 'mono',
    name: 'Smoke Grey',
    description: 'Deep neutral grey theme with soft charcoal surfaces',
    colors: {
      '--bg-primary': '#0f1114',
      '--bg-secondary': '#171a1e',
      '--bg-tertiary': '#21252b',
      '--bg-card': '#1a1e23',
      '--bg-card-hover': '#24282f',
      '--bg-hover': '#2e333b',
      '--bg-overlay': '#1a1e23',
      '--text-primary': '#eceef0',
      '--text-secondary': '#b0b6bd',
      '--text-muted': '#7e8790',
      '--text-inverse': '#0f1114',
      '--color-primary': '#e6e9eb',
      '--color-primary-hover': '#ffffff',
      '--color-primary-light': '#2a2f37',
      '--color-accent': '#c0c6cc',
      '--border-color': '#2a2f37',
      '--border-light': '#1f232a',
      '--border-heavy': '#454c55',
      '--border-focus': '#7e8790',
      '--scrollbar-track': '#171a1e',
      '--scrollbar-thumb': '#454c55',
      '--scrollbar-thumb-hover': '#7e8790',
      '--color-success': '#e6e9eb',
      '--color-warning': '#9aa3ac',
      '--color-danger': '#e6e9eb',
      '--color-purple': '#b0b6bd',
    },
  },
  bone: {
    id: 'bone',
    mode: 'light',
    palette: 'mono',
    name: 'Bone White',
    description: 'Warm off-white theme with gentle ivory surfaces',
    colors: {
      '--bg-primary': '#f7f5f1',
      '--bg-secondary': '#efece6',
      '--bg-tertiary': '#e4e0d6',
      '--bg-card': '#fbfaf7',
      '--bg-card-hover': '#f2efe8',
      '--bg-hover': '#e4e0d6',
      '--bg-overlay': '#fbfaf7',
      '--text-primary': '#3a3833',
      '--text-secondary': '#66625a',
      '--text-muted': '#8a857a',
      '--text-inverse': '#fbfaf7',
      '--color-primary': '#403d36',
      '--color-primary-hover': '#2a2823',
      '--color-primary-light': '#e6e2d9',
      '--color-accent': '#66625a',
      '--border-color': '#e4e0d6',
      '--border-light': '#ece8e0',
      '--border-heavy': '#b6b0a3',
      '--border-focus': '#66625a',
      '--scrollbar-track': '#efece6',
      '--scrollbar-thumb': '#b6b0a3',
      '--scrollbar-thumb-hover': '#403d36',
      '--color-success': '#403d36',
      '--color-warning': '#8a857a',
      '--color-danger': '#403d36',
      '--color-purple': '#8a857a',
    },
  },
  mint: {
    id: 'mint',
    mode: 'light',
    palette: 'duo',
    name: 'Mint Cream',
    description: 'Light pastel green theme with a fresh mint accent',
    colors: {
      '--bg-primary': '#f2faf6',
      '--bg-secondary': '#e6f5ee',
      '--bg-tertiary': '#d4ecdf',
      '--bg-card': '#f8fdfa',
      '--bg-card-hover': '#ecf8f2',
      '--bg-hover': '#d4ecdf',
      '--bg-overlay': '#f8fdfa',
      '--text-primary': '#1d3a2e',
      '--text-secondary': '#4d7867',
      '--text-muted': '#73988a',
      '--text-inverse': '#f8fdfa',
      '--color-primary': '#178a62',
      '--color-primary-hover': '#0f6b4c',
      '--color-primary-light': '#d1f0e3',
      '--color-accent': '#2f9e64',
      '--border-color': '#d4ecdf',
      '--border-light': '#e0f2e9',
      '--border-heavy': '#a8d4bd',
      '--border-focus': '#178a62',
      '--scrollbar-track': '#e6f5ee',
      '--scrollbar-thumb': '#a8d4bd',
      '--scrollbar-thumb-hover': '#178a62',
      '--color-success': '#178a62',
      '--color-warning': '#a16207',
      '--color-danger': '#b91c1c',
      '--color-purple': '#6d5bb8',
    },
  },
  crimson: {
    id: 'crimson',
    mode: 'dark',
    palette: 'tri',
    name: 'Crimson Tide',
    description: 'Deep crimson theme with bold scarlet highlights',
    colors: {
      '--bg-primary': '#17070a',
      '--bg-secondary': '#200a0f',
      '--bg-tertiary': '#2e1018',
      '--bg-card': '#230c12',
      '--bg-card-hover': '#2e1219',
      '--bg-hover': '#3c1a22',
      '--bg-overlay': '#230c12',
      '--text-primary': '#fdf0f2',
      '--text-secondary': '#eab4bd',
      '--text-muted': '#cf8b96',
      '--text-inverse': '#17070a',
      '--color-primary': '#d92640',
      '--color-primary-hover': '#b81d35',
      '--color-primary-light': '#4c1220',
      '--color-accent': '#ef4a62',
      '--border-color': '#3a1520',
      '--border-light': '#2a0e16',
      '--border-heavy': '#5c2030',
      '--border-focus': '#d92640',
      '--scrollbar-track': '#200a0f',
      '--scrollbar-thumb': '#5c2030',
      '--scrollbar-thumb-hover': '#d92640',
      '--color-success': '#2f9e64',
      '--color-warning': '#c47f1d',
      '--color-danger': '#d92640',
      '--color-purple': '#9b6bb5',
    },
  },
  indigo: {
    id: 'indigo',
    mode: 'dark',
    palette: 'tri',
    name: 'Indigo Night',
    description: 'Deep indigo theme with electric violet-blue highlights',
    colors: {
      '--bg-primary': '#0e0d1c',
      '--bg-secondary': '#151426',
      '--bg-tertiary': '#1f1d36',
      '--bg-card': '#181627',
      '--bg-card-hover': '#211e38',
      '--bg-hover': '#2b2847',
      '--bg-overlay': '#181627',
      '--text-primary': '#eef0ff',
      '--text-secondary': '#b6baf5',
      '--text-muted': '#8f94d8',
      '--text-inverse': '#0e0d1c',
      '--color-primary': '#5c63e0',
      '--color-primary-hover': '#454cc9',
      '--color-primary-light': '#2a2a52',
      '--color-accent': '#7b82f0',
      '--border-color': '#262344',
      '--border-light': '#1c1a34',
      '--border-heavy': '#3d3a68',
      '--border-focus': '#5c63e0',
      '--scrollbar-track': '#151426',
      '--scrollbar-thumb': '#3d3a68',
      '--scrollbar-thumb-hover': '#5c63e0',
      '--color-success': '#2f9e64',
      '--color-warning': '#c49a1d',
      '--color-danger': '#c4451e',
      '--color-purple': '#8b5cf6',
    },
  },
  petrol: {
    id: 'petrol',
    mode: 'dark',
    palette: 'tri',
    name: 'Petrol Depth',
    description: 'Dark petrol theme with cool teal highlights',
    colors: {
      '--bg-primary': '#0a1314',
      '--bg-secondary': '#101b1d',
      '--bg-tertiary': '#172629',
      '--bg-card': '#121d20',
      '--bg-card-hover': '#192a2d',
      '--bg-hover': '#213538',
      '--bg-overlay': '#121d20',
      '--text-primary': '#ecf6f7',
      '--text-secondary': '#a9cdd1',
      '--text-muted': '#7fa5aa',
      '--text-inverse': '#0a1314',
      '--color-primary': '#2aa8b5',
      '--color-primary-hover': '#1f8b96',
      '--color-primary-light': '#144650',
      '--color-accent': '#37c0ce',
      '--border-color': '#1f3336',
      '--border-light': '#172629',
      '--border-heavy': '#335055',
      '--border-focus': '#2aa8b5',
      '--scrollbar-track': '#101b1d',
      '--scrollbar-thumb': '#335055',
      '--scrollbar-thumb-hover': '#2aa8b5',
      '--color-success': '#2f9e64',
      '--color-warning': '#c49a1d',
      '--color-danger': '#c4451e',
      '--color-purple': '#8a7cc0',
    },
  },
  plum: {
    id: 'plum',
    mode: 'dark',
    palette: 'tri',
    name: 'Plum Noir',
    description: 'Deep plum theme with rosy mauve highlights',
    colors: {
      '--bg-primary': '#170b18',
      '--bg-secondary': '#201021',
      '--bg-tertiary': '#2d1830',
      '--bg-card': '#231226',
      '--bg-card-hover': '#2d1830',
      '--bg-hover': '#3b2140',
      '--bg-overlay': '#231226',
      '--text-primary': '#f9eef9',
      '--text-secondary': '#d4abd8',
      '--text-muted': '#b587ba',
      '--text-inverse': '#170b18',
      '--color-primary': '#b04ab8',
      '--color-primary-hover': '#973ba0',
      '--color-primary-light': '#3f1f47',
      '--color-accent': '#c66fd0',
      '--border-color': '#351b39',
      '--border-light': '#261329',
      '--border-heavy': '#552d5b',
      '--border-focus': '#b04ab8',
      '--scrollbar-track': '#201021',
      '--scrollbar-thumb': '#552d5b',
      '--scrollbar-thumb-hover': '#b04ab8',
      '--color-success': '#2f9e64',
      '--color-warning': '#c49a1d',
      '--color-danger': '#c4451e',
      '--color-purple': '#b04ab8',
    },
  },
  sunset: {
    id: 'sunset',
    mode: 'dark',
    palette: 'tetra',
    name: 'Sunset Vibes',
    description: 'Warm sunset theme with coral, orange, and peach tones',
    colors: {
      '--bg-primary': '#1a0f0c',
      '--bg-secondary': '#24130f',
      '--bg-tertiary': '#331c14',
      '--bg-card': '#261410',
      '--bg-card-hover': '#331c14',
      '--bg-hover': '#442818',
      '--bg-overlay': '#261410',
      '--text-primary': '#fff3ec',
      '--text-secondary': '#ffc3a3',
      '--text-muted': '#f29b70',
      '--text-inverse': '#1a0f0c',
      '--color-primary': '#ff7b3d',
      '--color-primary-hover': '#e8641f',
      '--color-primary-light': '#5c2b14',
      '--color-accent': '#ff9d63',
      '--border-color': '#45251a',
      '--border-light': '#2f1a12',
      '--border-heavy': '#6e3c29',
      '--border-focus': '#ff7b3d',
      '--scrollbar-track': '#24130f',
      '--scrollbar-thumb': '#6e3c29',
      '--scrollbar-thumb-hover': '#ff7b3d',
      '--color-success': '#3dd68c',
      '--color-warning': '#ffb340',
      '--color-danger': '#ff4d5e',
      '--color-purple': '#c07bff',
    },
  },
  aurora: {
    id: 'aurora',
    mode: 'dark',
    palette: 'tetra',
    name: 'Aurora Sky',
    description: 'Northern lights theme with teal, green, and violet tones',
    colors: {
      '--bg-primary': '#0a1318',
      '--bg-secondary': '#101c23',
      '--bg-tertiary': '#172933',
      '--bg-card': '#121f27',
      '--bg-card-hover': '#1a2b35',
      '--bg-hover': '#223845',
      '--bg-overlay': '#121f27',
      '--text-primary': '#ecf9f7',
      '--text-secondary': '#a7ded8',
      '--text-muted': '#79bcb8',
      '--text-inverse': '#0a1318',
      '--color-primary': '#23b5a0',
      '--color-primary-hover': '#189482',
      '--color-primary-light': '#104d46',
      '--color-accent': '#4bd6c0',
      '--border-color': '#1d3a3d',
      '--border-light': '#152a2e',
      '--border-heavy': '#2f5658',
      '--border-focus': '#23b5a0',
      '--scrollbar-track': '#101c23',
      '--scrollbar-thumb': '#2f5658',
      '--scrollbar-thumb-hover': '#23b5a0',
      '--color-success': '#3dd68c',
      '--color-warning': '#e8c44d',
      '--color-danger': '#f0789a',
      '--color-purple': '#9d7bf0',
    },
  },
  neon: {
    id: 'neon',
    mode: 'dark',
    palette: 'tetra',
    name: 'Neon District',
    description: 'Electric theme with cyan, magenta, and lime glow tones',
    colors: {
      '--bg-primary': '#0c0d16',
      '--bg-secondary': '#131426',
      '--bg-tertiary': '#1c1d38',
      '--bg-card': '#161730',
      '--bg-card-hover': '#1f203e',
      '--bg-hover': '#2a2c50',
      '--bg-overlay': '#161730',
      '--text-primary': '#eef0ff',
      '--text-secondary': '#b9c2ff',
      '--text-muted': '#8a97e8',
      '--text-inverse': '#0c0d16',
      '--color-primary': '#00e5ff',
      '--color-primary-hover': '#00b8d6',
      '--color-primary-light': '#0a4a5e',
      '--color-accent': '#ff3df0',
      '--border-color': '#272952',
      '--border-light': '#1c1d3a',
      '--border-heavy': '#3e4180',
      '--border-focus': '#00e5ff',
      '--scrollbar-track': '#131426',
      '--scrollbar-thumb': '#3e4180',
      '--scrollbar-thumb-hover': '#00e5ff',
      '--color-success': '#7aff6b',
      '--color-warning': '#ffe14d',
      '--color-danger': '#ff4d6e',
      '--color-purple': '#b26bff',
    },
  },
  galaxy: {
    id: 'galaxy',
    mode: 'dark',
    palette: 'tetra',
    name: 'Galaxy Deep',
    description: 'Deep space theme with indigo, violet, and magenta tones',
    colors: {
      '--bg-primary': '#0e0b1f',
      '--bg-secondary': '#150f2b',
      '--bg-tertiary': '#1e163e',
      '--bg-card': '#181129',
      '--bg-card-hover': '#211a38',
      '--bg-hover': '#2c2350',
      '--bg-overlay': '#181129',
      '--text-primary': '#f1efff',
      '--text-secondary': '#c4b9f7',
      '--text-muted': '#9c90d9',
      '--text-inverse': '#0e0b1f',
      '--color-primary': '#6d5ce8',
      '--color-primary-hover': '#5546ce',
      '--color-primary-light': '#2c2158',
      '--color-accent': '#c04be0',
      '--border-color': '#2a2050',
      '--border-light': '#1e1639',
      '--border-heavy': '#453a7d',
      '--border-focus': '#6d5ce8',
      '--scrollbar-track': '#150f2b',
      '--scrollbar-thumb': '#453a7d',
      '--scrollbar-thumb-hover': '#6d5ce8',
      '--color-success': '#4bd6a0',
      '--color-warning': '#f0c24d',
      '--color-danger': '#f05a8a',
      '--color-purple': '#9d7bf0',
    },
  },
  paradise: {
    id: 'paradise',
    mode: 'dark',
    palette: 'tetra',
    name: 'Tropical Paradise',
    description: 'Lush theme with teal, coral, and sunshine yellow tones',
    colors: {
      '--bg-primary': '#0c1715',
      '--bg-secondary': '#12211e',
      '--bg-tertiary': '#1a302b',
      '--bg-card': '#142421',
      '--bg-card-hover': '#1c302a',
      '--bg-hover': '#253d36',
      '--bg-overlay': '#142421',
      '--text-primary': '#f0fbf8',
      '--text-secondary': '#b0e8db',
      '--text-muted': '#83c4b2',
      '--text-inverse': '#0c1715',
      '--color-primary': '#19c9a6',
      '--color-primary-hover': '#12a98b',
      '--color-primary-light': '#0e4d40',
      '--color-accent': '#ff8a5c',
      '--border-color': '#24423b',
      '--border-light': '#19302a',
      '--border-heavy': '#396558',
      '--border-focus': '#19c9a6',
      '--scrollbar-track': '#12211e',
      '--scrollbar-thumb': '#396558',
      '--scrollbar-thumb-hover': '#19c9a6',
      '--color-success': '#4bd6a0',
      '--color-warning': '#ffd257',
      '--color-danger': '#ff6b7a',
      '--color-purple': '#8f8bff',
    },
  },
  festival: {
    id: 'festival',
    mode: 'dark',
    palette: 'tetra',
    name: 'Festival Pop',
    description: 'Celebratory theme with hot pink, gold, and violet tones',
    colors: {
      '--bg-primary': '#1a0f1a',
      '--bg-secondary': '#241424',
      '--bg-tertiary': '#331d33',
      '--bg-card': '#261626',
      '--bg-card-hover': '#331d33',
      '--bg-hover': '#442744',
      '--bg-overlay': '#261626',
      '--text-primary': '#fdf1fd',
      '--text-secondary': '#e8b8e8',
      '--text-muted': '#cf8fcf',
      '--text-inverse': '#1a0f1a',
      '--color-primary': '#ff4d9d',
      '--color-primary-hover': '#e62b80',
      '--color-primary-light': '#5c1f47',
      '--color-accent': '#ffd24d',
      '--border-color': '#452645',
      '--border-light': '#2f1a2f',
      '--border-heavy': '#6e3c6e',
      '--border-focus': '#ff4d9d',
      '--scrollbar-track': '#241424',
      '--scrollbar-thumb': '#6e3c6e',
      '--scrollbar-thumb-hover': '#ff4d9d',
      '--color-success': '#4dd68c',
      '--color-warning': '#ffd24d',
      '--color-danger': '#ff5b6e',
      '--color-purple': '#c77bff',
    },
  },
  prism: {
    id: 'prism',
    mode: 'dark',
    palette: 'tetra',
    name: 'Prismatic',
    description: 'Balanced theme with red, blue, and amber primary tones',
    colors: {
      '--bg-primary': '#151218',
      '--bg-secondary': '#1e1a23',
      '--bg-tertiary': '#2a2530',
      '--bg-card': '#211c28',
      '--bg-card-hover': '#2b2533',
      '--bg-hover': '#383043',
      '--bg-overlay': '#211c28',
      '--text-primary': '#f5f2f7',
      '--text-secondary': '#c5bdd0',
      '--text-muted': '#a091a8',
      '--text-inverse': '#151218',
      '--color-primary': '#e05c5c',
      '--color-primary-hover': '#c44242',
      '--color-primary-light': '#4a2323',
      '--color-accent': '#5c9ae0',
      '--border-color': '#2f2937',
      '--border-light': '#241f2b',
      '--border-heavy': '#4b4254',
      '--border-focus': '#e05c5c',
      '--scrollbar-track': '#1e1a23',
      '--scrollbar-thumb': '#4b4254',
      '--scrollbar-thumb-hover': '#e05c5c',
      '--color-success': '#4dd68c',
      '--color-warning': '#e8c44d',
      '--color-danger': '#ff5b6e',
      '--color-purple': '#9d7bf0',
    },
  },
  cosmic: {
    id: 'cosmic',
    mode: 'dark',
    palette: 'tetra',
    name: 'Cosmic Dust',
    description: 'Nebula theme with violet, blue, and rose tones',
    colors: {
      '--bg-primary': '#120c1a',
      '--bg-secondary': '#1a1226',
      '--bg-tertiary': '#261a36',
      '--bg-card': '#1d1429',
      '--bg-card-hover': '#271b38',
      '--bg-hover': '#342648',
      '--bg-overlay': '#1d1429',
      '--text-primary': '#f4effb',
      '--text-secondary': '#cabde8',
      '--text-muted': '#a395c6',
      '--text-inverse': '#120c1a',
      '--color-primary': '#7a5ad4',
      '--color-primary-hover': '#6343ba',
      '--color-primary-light': '#332052',
      '--color-accent': '#e0609d',
      '--border-color': '#2f2248',
      '--border-light': '#231935',
      '--border-heavy': '#4d3a70',
      '--border-focus': '#7a5ad4',
      '--scrollbar-track': '#1a1226',
      '--scrollbar-thumb': '#4d3a70',
      '--scrollbar-thumb-hover': '#7a5ad4',
      '--color-success': '#4dd6a0',
      '--color-warning': '#e8c44d',
      '--color-danger': '#ff5b8a',
      '--color-purple': '#9d7bf0',
    },
  },
}

export const PALETTE_GROUPS = [
  {
    id: 'mono',
    label: 'Monochrome',
    description: 'Pure black, white, and grey themes built from a single tonal family.',
  },
  {
    id: 'duo',
    label: 'Two Color',
    description: 'A neutral or warm canvas with one signature accent hue.',
  },
  {
    id: 'tri',
    label: 'Tri Color',
    description: 'Deep colored bases layered with a contrasting accent tone.',
  },
  {
    id: 'tetra',
    label: 'Tetra Color',
    description: 'Vibrant multi-hue palettes combining three or more distinct colors.',
  },
]

export function getPresetsByPalette(paletteId) {
  return Object.values(THEME_PRESETS).filter((preset) => preset.palette === paletteId)
}

export const FONT_OPTIONS = [
  { id: 'inter', name: 'Inter (Default)', value: "'Inter', sans-serif" },
  { id: 'roboto', name: 'Roboto', value: "'Roboto', sans-serif" },
  { id: 'outfit', name: 'Outfit', value: "'Outfit', sans-serif" },
  { id: 'jakarta', name: 'Plus Jakarta Sans', value: "'Plus Jakarta Sans', sans-serif" },
  { id: 'fira', name: 'Fira Code (Monospace)', value: "'Fira Code', monospace" },
  { id: 'system', name: 'System Default UI', value: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" },
]

export const RADIUS_OPTIONS = [
  {
    id: 'sharp',
    name: 'Sharp (0px)',
    tokens: {
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
    },
  },
  {
    id: 'subtle',
    name: 'Subtle (4px)',
    tokens: {
      '--radius-xs': '2px',
      '--radius-sm': '4px',
      '--radius-md': '6px',
      '--radius-lg': '8px',
      '--radius-xl': '10px',
    },
  },
  {
    id: 'modern',
    name: 'Modern Soft (9px)',
    tokens: {
      '--radius-xs': '4px',
      '--radius-sm': '6px',
      '--radius-md': '9px',
      '--radius-lg': '12px',
      '--radius-xl': '16px',
    },
  },
  {
    id: 'rounded',
    name: 'Rounded (16px)',
    tokens: {
      '--radius-xs': '6px',
      '--radius-sm': '10px',
      '--radius-md': '14px',
      '--radius-lg': '18px',
      '--radius-xl': '24px',
    },
  },
  {
    id: 'bubble',
    name: 'Curved Bubble (24px)',
    tokens: {
      '--radius-xs': '8px',
      '--radius-sm': '14px',
      '--radius-md': '20px',
      '--radius-lg': '28px',
      '--radius-xl': '36px',
    },
  },
]

export const DENSITY_OPTIONS = [
  {
    id: 'compact',
    name: 'Compact (Power User)',
    tokens: {
      '--layout-card-padding': '12px',
      '--layout-section-gap': '16px',
      '--layout-gutter': '16px',
    },
  },
  {
    id: 'default',
    name: 'Default Balanced',
    tokens: {
      '--layout-card-padding': 'clamp(16px, 1.8vw, 22px)',
      '--layout-section-gap': 'clamp(18px, 2.2vw, 28px)',
      '--layout-gutter': 'clamp(16px, 3vw, 40px)',
    },
  },
  {
    id: 'spacious',
    name: 'Spacious (Relaxed)',
    tokens: {
      '--layout-card-padding': '28px',
      '--layout-section-gap': '36px',
      '--layout-gutter': '48px',
    },
  },
]

export const ELEVATION_OPTIONS = [
  {
    id: 'flat',
    name: 'Flat Minimalist (No Shadows)',
    tokens: {
      '--shadow-sm': 'none',
      '--shadow-md': 'none',
      '--shadow-lg': 'none',
      '--shadow-surface': 'none',
    },
  },
  {
    id: 'subtle',
    name: 'Subtle Modern Elevation',
    tokens: {
      '--shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.04)',
      '--shadow-md': '0 4px 8px rgba(0, 0, 0, 0.06)',
      '--shadow-lg': '0 12px 30px rgba(0, 0, 0, 0.1)',
      '--shadow-surface': '0 2px 8px rgba(0, 0, 0, 0.05)',
    },
  },
  {
    id: 'deep',
    name: 'Deep 3D Floating Surfaces',
    tokens: {
      '--shadow-sm': '0 2px 6px rgba(0, 0, 0, 0.12)',
      '--shadow-md': '0 8px 24px rgba(0, 0, 0, 0.18)',
      '--shadow-lg': '0 25px 60px rgba(0, 0, 0, 0.28)',
      '--shadow-surface': '0 4px 18px rgba(0, 0, 0, 0.15)',
    },
  },
]

export const MOTION_OPTIONS = [
  {
    id: 'none',
    name: 'Instant (0ms)',
    tokens: {
      '--transition-fast': '0ms',
      '--transition-normal': '0ms',
      '--transition-slow': '0ms',
    },
  },
  {
    id: 'fast',
    name: 'Fast Snap (100ms)',
    tokens: {
      '--transition-fast': '80ms ease',
      '--transition-normal': '120ms ease',
      '--transition-slow': '180ms ease',
    },
  },
  {
    id: 'normal',
    name: 'Smooth Default (200ms)',
    tokens: {
      '--transition-fast': '140ms ease',
      '--transition-normal': '200ms ease',
      '--transition-slow': '300ms ease',
    },
  },
  {
    id: 'relaxed',
    name: 'Relaxed Fluid (350ms)',
    tokens: {
      '--transition-fast': '200ms ease',
      '--transition-normal': '350ms ease',
      '--transition-slow': '500ms ease',
    },
  },
]

export const COLOR_VARIABLE_GROUPS = [
  {
    title: 'Main & Surface Backgrounds',
    variables: [
      { key: '--bg-primary', label: 'Main Page Background' },
      { key: '--bg-secondary', label: 'Sidebar & Header Background' },
      { key: '--bg-tertiary', label: 'Sub-panel Background' },
      { key: '--bg-card', label: 'Card & Container Surface' },
      { key: '--bg-card-hover', label: 'Card Hover Background' },
      { key: '--bg-hover', label: 'Interactive Hover Background' },
      { key: '--bg-overlay', label: 'Modal & Popover Surface' },
    ],
  },
  {
    title: 'Text & Typography',
    variables: [
      { key: '--text-primary', label: 'Primary Heading & Body Text' },
      { key: '--text-secondary', label: 'Secondary / Subtitle Text' },
      { key: '--text-muted', label: 'Muted / Caption Text' },
      { key: '--text-inverse', label: 'Button & Inverted Text' },
    ],
  },
  {
    title: 'Buttons & Accents',
    variables: [
      { key: '--color-primary', label: 'Primary Button & Active Fill' },
      { key: '--color-primary-hover', label: 'Primary Button Hover Fill' },
      { key: '--color-primary-light', label: 'Primary Light Badge Tint' },
      { key: '--color-accent', label: 'Accent Highlight' },
    ],
  },
  {
    title: 'Borders & Lines',
    variables: [
      { key: '--border-color', label: 'Standard Component Border' },
      { key: '--border-light', label: 'Light Separator Line' },
      { key: '--border-heavy', label: 'High Contrast Border' },
      { key: '--border-focus', label: 'Active Input Focus Ring' },
    ],
  },
  {
    title: 'Scrollbars',
    variables: [
      { key: '--scrollbar-track', label: 'Scrollbar Track' },
      { key: '--scrollbar-thumb', label: 'Scrollbar Thumb' },
      { key: '--scrollbar-thumb-hover', label: 'Scrollbar Thumb Hover' },
    ],
  },
  {
    title: 'Status & Badges',
    variables: [
      { key: '--color-success', label: 'Success Tag / Indicator' },
      { key: '--color-warning', label: 'Warning Tag / Indicator' },
      { key: '--color-danger', label: 'Danger / Error Tag' },
      { key: '--color-purple', label: 'Special / Category Tag' },
    ],
  },
]

const STORAGE_KEY = 'starwaves.custom_theme'

export function applyThemeVariables(data) {
  if (!data || typeof data !== 'object') return
  const root = document.documentElement

  // Apply colors
  if (data.colors && typeof data.colors === 'object') {
    Object.entries(data.colors).forEach(([property, value]) => {
      if (property.startsWith('--') && value) {
        root.style.setProperty(property, value)
      }
    })
  }

  // Apply Font
  if (data.fontFamily) {
    const fontOpt = FONT_OPTIONS.find((f) => f.id === data.fontFamily)
    if (fontOpt) {
      root.style.setProperty('--font-family', fontOpt.value)
    }
  }

  // Apply Radius
  if (data.radius) {
    const radOpt = RADIUS_OPTIONS.find((r) => r.id === data.radius)
    if (radOpt) {
      Object.entries(radOpt.tokens).forEach(([k, v]) => root.style.setProperty(k, v))
    }
  }

  // Apply Density
  if (data.density) {
    const denOpt = DENSITY_OPTIONS.find((d) => d.id === data.density)
    if (denOpt) {
      Object.entries(denOpt.tokens).forEach(([k, v]) => root.style.setProperty(k, v))
    }
  }

  // Apply Elevation
  if (data.elevation) {
    const elevOpt = ELEVATION_OPTIONS.find((e) => e.id === data.elevation)
    if (elevOpt) {
      Object.entries(elevOpt.tokens).forEach(([k, v]) => root.style.setProperty(k, v))
    }
  }

  // Apply Motion
  if (data.motion) {
    const motOpt = MOTION_OPTIONS.find((m) => m.id === data.motion)
    if (motOpt) {
      Object.entries(motOpt.tokens).forEach(([k, v]) => root.style.setProperty(k, v))
    }
  }
}

export function resetThemeVariables() {
  const root = document.documentElement
  COLOR_VARIABLE_GROUPS.forEach((group) => {
    group.variables.forEach((item) => {
      root.style.removeProperty(item.key)
    })
  })
  root.style.removeProperty('--font-family')
  if (RADIUS_OPTIONS[2].tokens) {
    Object.keys(RADIUS_OPTIONS[2].tokens).forEach((k) => root.style.removeProperty(k))
  }
  if (DENSITY_OPTIONS[1].tokens) {
    Object.keys(DENSITY_OPTIONS[1].tokens).forEach((k) => root.style.removeProperty(k))
  }
  if (ELEVATION_OPTIONS[1].tokens) {
    Object.keys(ELEVATION_OPTIONS[1].tokens).forEach((k) => root.style.removeProperty(k))
  }
  if (MOTION_OPTIONS[2].tokens) {
    Object.keys(MOTION_OPTIONS[2].tokens).forEach((k) => root.style.removeProperty(k))
  }
}

export function useThemeCustomizer() {
  const [themeState, setThemeState] = useState(() => {
    const saved = localStorage.getItem(STORAGE_KEY)
    if (saved) {
      try {
        const parsed = JSON.parse(saved)
        return {
          preset: parsed.preset || 'custom',
          colors: parsed.colors || THEME_PRESETS.dark.colors,
          fontFamily: parsed.fontFamily || 'inter',
          radius: parsed.radius || 'modern',
          density: parsed.density || 'default',
          elevation: parsed.elevation || 'subtle',
          motion: parsed.motion || 'normal',
        }
      } catch {
        /* fallback */
      }
    }
    const isDark = localStorage.getItem('starwaves.theme') === 'dark'
    return {
      preset: isDark ? 'dark' : 'light',
      colors: THEME_PRESETS[isDark ? 'dark' : 'light'].colors,
      fontFamily: 'inter',
      radius: 'modern',
      density: 'default',
      elevation: 'subtle',
      motion: 'normal',
    }
  })

  const [isSaved, setIsSaved] = useState(false)

  useEffect(() => {
    applyThemeVariables(themeState)
  }, [themeState])

  const selectPreset = useCallback((presetId) => {
    const preset = THEME_PRESETS[presetId]
    if (!preset) return
    const isDarkPreset = preset.mode === 'dark'
    const nextState = {
      ...themeState,
      preset: presetId,
      colors: preset.colors,
    }
    setThemeState(nextState)
    document.documentElement.classList.toggle('dark-theme', isDarkPreset)
    localStorage.setItem('starwaves.theme', isDarkPreset ? 'dark' : 'light')
    localStorage.setItem(STORAGE_KEY, JSON.stringify(nextState))
    setIsSaved(true)
    setTimeout(() => setIsSaved(false), 2000)
  }, [themeState])

  const updateColor = useCallback((variableKey, colorValue) => {
    setThemeState((prev) => {
      const next = {
        ...prev,
        preset: 'custom',
        colors: { ...prev.colors, [variableKey]: colorValue },
      }
      localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
      return next
    })
  }, [])

  const updateOption = useCallback((optionKey, value) => {
    setThemeState((prev) => {
      const next = { ...prev, [optionKey]: value }
      localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
      return next
    })
    setIsSaved(true)
    setTimeout(() => setIsSaved(false), 2000)
  }, [])

  const saveCustomTheme = useCallback(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(themeState))
    setIsSaved(true)
    setTimeout(() => setIsSaved(false), 2000)
  }, [themeState])

  const resetToDefault = useCallback(() => {
    localStorage.removeItem(STORAGE_KEY)
    resetThemeVariables()
    const isDark = localStorage.getItem('starwaves.theme') === 'dark'
    const defaultPreset = isDark ? 'dark' : 'light'
    const defaultState = {
      preset: defaultPreset,
      colors: THEME_PRESETS[defaultPreset].colors,
      fontFamily: 'inter',
      radius: 'modern',
      density: 'default',
      elevation: 'subtle',
      motion: 'normal',
    }
    setThemeState(defaultState)
    setIsSaved(true)
    setTimeout(() => setIsSaved(false), 2000)
  }, [])

  const exportTheme = useCallback(() => {
    const dataStr =
      'data:text/json;charset=utf-8,' +
      encodeURIComponent(JSON.stringify(themeState, null, 2))
    const downloadAnchor = document.createElement('a')
    downloadAnchor.setAttribute('href', dataStr)
    downloadAnchor.setAttribute(
      'download',
      `starwaves-ui-ux-${themeState.preset || 'custom'}.json`,
    )
    document.body.appendChild(downloadAnchor)
    downloadAnchor.click()
    downloadAnchor.remove()
  }, [themeState])

  const importTheme = useCallback((themeData) => {
    if (themeData) {
      const nextState = {
        preset: themeData.preset || 'custom',
        colors: themeData.colors || THEME_PRESETS.dark.colors,
        fontFamily: themeData.fontFamily || 'inter',
        radius: themeData.radius || 'modern',
        density: themeData.density || 'default',
        elevation: themeData.elevation || 'subtle',
        motion: themeData.motion || 'normal',
      }
      setThemeState(nextState)
      localStorage.setItem(STORAGE_KEY, JSON.stringify(nextState))
      setIsSaved(true)
      setTimeout(() => setIsSaved(false), 2000)
    }
  }, [])

  return {
    activePreset: themeState.preset,
    currentColors: themeState.colors,
    fontFamily: themeState.fontFamily,
    radius: themeState.radius,
    density: themeState.density,
    elevation: themeState.elevation,
    motion: themeState.motion,
    isSaved,
    selectPreset,
    updateColor,
    updateOption,
    saveCustomTheme,
    resetToDefault,
    exportTheme,
    importTheme,
  }
}
